export interface AirportEntry {
  code: string;
  /** 機場全名，供「出發地/目的地」自動完成下拉選單顯示用 */
  name: string;
  city: string;
  country: string;
  /** ISO alpha-2 國碼（小寫），供旅行地圖依國家分色使用 */
  countryCode: string;
  lat: number;
  lng: number;
}

/** 常用機場資料（含座標／國碼），供「行程」出發地/目的地自動完成使用（僅列機場，不做一般地址搜尋） */
export const AIRPORT_DIRECTORY: AirportEntry[] = [
  {
    code: 'TPE',
    name: '臺灣桃園國際機場',
    city: '台北(桃園)',
    country: '台灣',
    countryCode: 'tw',
    lat: 24.9931,
    lng: 121.2251,
  },
  {
    code: 'TSA',
    name: '台北松山機場',
    city: '台北(松山)',
    country: '台灣',
    countryCode: 'tw',
    lat: 25.0694,
    lng: 121.5522,
  },
  {
    code: 'KHH',
    name: '高雄國際機場',
    city: '高雄',
    country: '台灣',
    countryCode: 'tw',
    lat: 22.5771,
    lng: 120.3499,
  },
  {
    code: 'RMQ',
    name: '台中國際機場',
    city: '台中',
    country: '台灣',
    countryCode: 'tw',
    lat: 24.2647,
    lng: 120.6236,
  },
  {
    code: 'NRT',
    name: '東京成田國際機場',
    city: '東京(成田)',
    country: '日本',
    countryCode: 'jp',
    lat: 35.772,
    lng: 140.3929,
  },
  {
    code: 'HND',
    name: '東京羽田機場',
    city: '東京(羽田)',
    country: '日本',
    countryCode: 'jp',
    lat: 35.5494,
    lng: 139.7798,
  },
  {
    code: 'KIX',
    name: '大阪關西國際機場',
    city: '大阪',
    country: '日本',
    countryCode: 'jp',
    lat: 34.4347,
    lng: 135.2441,
  },
  {
    code: 'NGO',
    name: '中部國際機場',
    city: '名古屋',
    country: '日本',
    countryCode: 'jp',
    lat: 34.8584,
    lng: 136.8054,
  },
  {
    code: 'FUK',
    name: '福岡機場',
    city: '福岡',
    country: '日本',
    countryCode: 'jp',
    lat: 33.5859,
    lng: 130.4517,
  },
  {
    code: 'CTS',
    name: '新千歲機場',
    city: '札幌',
    country: '日本',
    countryCode: 'jp',
    lat: 42.7752,
    lng: 141.6923,
  },
  {
    code: 'OKA',
    name: '那霸機場',
    city: '沖繩',
    country: '日本',
    countryCode: 'jp',
    lat: 26.1958,
    lng: 127.6458,
  },
  {
    code: 'ICN',
    name: '首爾仁川國際機場',
    city: '首爾(仁川)',
    country: '南韓',
    countryCode: 'kr',
    lat: 37.4602,
    lng: 126.4407,
  },
  {
    code: 'GMP',
    name: '首爾金浦機場',
    city: '首爾(金浦)',
    country: '南韓',
    countryCode: 'kr',
    lat: 37.5583,
    lng: 126.7906,
  },
  {
    code: 'PUS',
    name: '釜山金海國際機場',
    city: '釜山',
    country: '南韓',
    countryCode: 'kr',
    lat: 35.1795,
    lng: 128.9382,
  },
  {
    code: 'HKG',
    name: '香港國際機場',
    city: '香港',
    country: '香港',
    countryCode: 'hk',
    lat: 22.308,
    lng: 113.9185,
  },
  {
    code: 'MFM',
    name: '澳門國際機場',
    city: '澳門',
    country: '澳門',
    countryCode: 'mo',
    lat: 22.1496,
    lng: 113.5915,
  },
  {
    code: 'PVG',
    name: '上海浦東國際機場',
    city: '上海(浦東)',
    country: '中國',
    countryCode: 'cn',
    lat: 31.1443,
    lng: 121.8083,
  },
  {
    code: 'SHA',
    name: '上海虹橋國際機場',
    city: '上海(虹橋)',
    country: '中國',
    countryCode: 'cn',
    lat: 31.1979,
    lng: 121.3363,
  },
  {
    code: 'PEK',
    name: '北京首都國際機場',
    city: '北京(首都)',
    country: '中國',
    countryCode: 'cn',
    lat: 40.0801,
    lng: 116.5846,
  },
  {
    code: 'PKX',
    name: '北京大興國際機場',
    city: '北京(大興)',
    country: '中國',
    countryCode: 'cn',
    lat: 39.5098,
    lng: 116.4109,
  },
  {
    code: 'CAN',
    name: '廣州白雲國際機場',
    city: '廣州',
    country: '中國',
    countryCode: 'cn',
    lat: 23.3924,
    lng: 113.2988,
  },
  {
    code: 'SZX',
    name: '深圳寶安國際機場',
    city: '深圳',
    country: '中國',
    countryCode: 'cn',
    lat: 22.6393,
    lng: 113.8107,
  },
  {
    code: 'BKK',
    name: '曼谷素萬那普國際機場',
    city: '曼谷',
    country: '泰國',
    countryCode: 'th',
    lat: 13.69,
    lng: 100.7501,
  },
  {
    code: 'DMK',
    name: '曼谷廊曼國際機場',
    city: '曼谷(廊曼)',
    country: '泰國',
    countryCode: 'th',
    lat: 13.9126,
    lng: 100.6068,
  },
  {
    code: 'HKT',
    name: '普吉國際機場',
    city: '普吉島',
    country: '泰國',
    countryCode: 'th',
    lat: 8.1132,
    lng: 98.3169,
  },
  {
    code: 'CNX',
    name: '清邁國際機場',
    city: '清邁',
    country: '泰國',
    countryCode: 'th',
    lat: 18.7669,
    lng: 98.9626,
  },
  {
    code: 'SGN',
    name: '胡志明市新山一國際機場',
    city: '胡志明市',
    country: '越南',
    countryCode: 'vn',
    lat: 10.8188,
    lng: 106.652,
  },
  {
    code: 'HAN',
    name: '河內內排國際機場',
    city: '河內',
    country: '越南',
    countryCode: 'vn',
    lat: 21.2212,
    lng: 105.8072,
  },
  {
    code: 'DAD',
    name: '峴港國際機場',
    city: '峴港',
    country: '越南',
    countryCode: 'vn',
    lat: 16.0439,
    lng: 108.199,
  },
  {
    code: 'SIN',
    name: '新加坡樟宜機場',
    city: '新加坡',
    country: '新加坡',
    countryCode: 'sg',
    lat: 1.3644,
    lng: 103.9915,
  },
  {
    code: 'KUL',
    name: '吉隆坡國際機場',
    city: '吉隆坡',
    country: '馬來西亞',
    countryCode: 'my',
    lat: 2.7456,
    lng: 101.7099,
  },
  {
    code: 'CGK',
    name: '雅加達蘇加諾-哈達國際機場',
    city: '雅加達',
    country: '印尼',
    countryCode: 'id',
    lat: -6.1256,
    lng: 106.6559,
  },
  {
    code: 'DPS',
    name: '峇里島伍拉·賴國際機場',
    city: '峇里島',
    country: '印尼',
    countryCode: 'id',
    lat: -8.7482,
    lng: 115.1675,
  },
  {
    code: 'MNL',
    name: '馬尼拉尼諾伊·艾奎諾國際機場',
    city: '馬尼拉',
    country: '菲律賓',
    countryCode: 'ph',
    lat: 14.5086,
    lng: 121.0194,
  },
  {
    code: 'CEB',
    name: '宿霧麥克坦國際機場',
    city: '宿霧',
    country: '菲律賓',
    countryCode: 'ph',
    lat: 10.3075,
    lng: 123.9789,
  },
  {
    code: 'DEL',
    name: '新德里英迪拉·甘地國際機場',
    city: '新德里',
    country: '印度',
    countryCode: 'in',
    lat: 28.5562,
    lng: 77.1,
  },
  {
    code: 'BOM',
    name: '孟買賈特拉帕蒂·希瓦吉國際機場',
    city: '孟買',
    country: '印度',
    countryCode: 'in',
    lat: 19.0887,
    lng: 72.8679,
  },
  {
    code: 'DXB',
    name: '杜拜國際機場',
    city: '杜拜',
    country: '阿聯酋',
    countryCode: 'ae',
    lat: 25.2532,
    lng: 55.3657,
  },
  {
    code: 'DOH',
    name: '哈馬德國際機場',
    city: '杜哈',
    country: '卡達',
    countryCode: 'qa',
    lat: 25.2731,
    lng: 51.6081,
  },
  {
    code: 'IST',
    name: '伊斯坦堡機場',
    city: '伊斯坦堡',
    country: '土耳其',
    countryCode: 'tr',
    lat: 41.2753,
    lng: 28.7519,
  },
  {
    code: 'LHR',
    name: '倫敦希斯洛機場',
    city: '倫敦',
    country: '英國',
    countryCode: 'gb',
    lat: 51.47,
    lng: -0.4543,
  },
  {
    code: 'CDG',
    name: '巴黎戴高樂機場',
    city: '巴黎',
    country: '法國',
    countryCode: 'fr',
    lat: 49.0097,
    lng: 2.5479,
  },
  {
    code: 'FRA',
    name: '法蘭克福機場',
    city: '法蘭克福',
    country: '德國',
    countryCode: 'de',
    lat: 50.0379,
    lng: 8.5622,
  },
  {
    code: 'FCO',
    name: '羅馬菲烏米奇諾機場',
    city: '羅馬',
    country: '義大利',
    countryCode: 'it',
    lat: 41.8003,
    lng: 12.2389,
  },
  {
    code: 'AMS',
    name: '阿姆斯特丹史基浦機場',
    city: '阿姆斯特丹',
    country: '荷蘭',
    countryCode: 'nl',
    lat: 52.3105,
    lng: 4.7683,
  },
  {
    code: 'ZRH',
    name: '蘇黎世機場',
    city: '蘇黎世',
    country: '瑞士',
    countryCode: 'ch',
    lat: 47.4647,
    lng: 8.5492,
  },
  {
    code: 'JFK',
    name: '紐約甘迺迪國際機場',
    city: '紐約',
    country: '美國',
    countryCode: 'us',
    lat: 40.6413,
    lng: -73.7781,
  },
  {
    code: 'LAX',
    name: '洛杉磯國際機場',
    city: '洛杉磯',
    country: '美國',
    countryCode: 'us',
    lat: 33.9416,
    lng: -118.4085,
  },
  {
    code: 'SFO',
    name: '舊金山國際機場',
    city: '舊金山',
    country: '美國',
    countryCode: 'us',
    lat: 37.6213,
    lng: -122.379,
  },
  {
    code: 'SEA',
    name: '西雅圖塔科馬國際機場',
    city: '西雅圖',
    country: '美國',
    countryCode: 'us',
    lat: 47.4502,
    lng: -122.3088,
  },
  {
    code: 'YVR',
    name: '溫哥華國際機場',
    city: '溫哥華',
    country: '加拿大',
    countryCode: 'ca',
    lat: 49.1947,
    lng: -123.1792,
  },
  {
    code: 'YYZ',
    name: '多倫多皮爾遜國際機場',
    city: '多倫多',
    country: '加拿大',
    countryCode: 'ca',
    lat: 43.6777,
    lng: -79.6248,
  },
  {
    code: 'SYD',
    name: '雪梨金斯福史密斯機場',
    city: '雪梨',
    country: '澳洲',
    countryCode: 'au',
    lat: -33.9399,
    lng: 151.1753,
  },
  {
    code: 'MEL',
    name: '墨爾本機場',
    city: '墨爾本',
    country: '澳洲',
    countryCode: 'au',
    lat: -37.669,
    lng: 144.841,
  },
  {
    code: 'AKL',
    name: '奧克蘭機場',
    city: '奧克蘭',
    country: '紐西蘭',
    countryCode: 'nz',
    lat: -37.0082,
    lng: 174.785,
  },
];

/** 依關鍵字（城市／機場全名／國家／機場代碼皆可）過濾機場清單，供出發地/目的地自動完成使用 */
export function filterAirportDirectory(query: string, limit = 8): AirportEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return AIRPORT_DIRECTORY.filter(
    (a) =>
      a.city.toLowerCase().includes(q) ||
      a.name.toLowerCase().includes(q) ||
      a.country.toLowerCase().includes(q) ||
      a.code.toLowerCase().includes(q),
  ).slice(0, limit);
}
